name = "discord-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Uncomment to use a custom domain
# routes = [
#   { pattern = "api.yourdomain.com", custom_domain = true }
# ]

[env.production]
vars = { ENVIRONMENT = "production" }